export enum BadgeType {
    THUNDER_BADGE = 'THUNDER_BADGE',
    FAIL_BADGE = 'FAIL_BADGE',
    SUCCESS_BADGE = 'SUCCESS_BADGE',
    DROUGHT_BADGE = 'DROUGHT_BADGE',
    FLOOD_BADGE = 'FLOOD_BADGE',
    IMPACT_BADGE = 'IMPACT_BADGE'
}
